import "../globals.css"

export const metadata = {
  title: 'Burhan"s Site',
  description: 'Generated by NextJS 13 & sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
