import Link from 'next/link'
import '../globals.css'
import { getPages } from '@/sanity/sanity-utils'

export const metadata = {
  title: 'Burhan"s Site',
  description: 'Generated by NextJS 13 & sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // get all our pages
  const pages = await getPages()
  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10'>
        <header className='flex items-center justify-between'>
          <Link href="/"
            className='bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold'
          >
            M.B
          </Link>
          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page)=>(
              <Link key={page._id} href={`/${page.slug}`} 
                className='underline hover:underline-offset-4 hover:text-red-700 transition'
              >
                {page.title}
              </Link>
            ))}
          </div>

        </header>
        <main className='py-20'>
          {children}
        </main>
      </body>
    </html>
  )
}
